CREATE TABLE IF NOT EXISTS users
(
    id           BIGINT NOT NULL,
    first_name   VARCHAR(128),
    last_name    VARCHAR(128),
    user_name    VARCHAR(128),
    registered   TIMESTAMP WITHOUT TIME ZONE,
    notification BOOLEAN,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS cards
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT,
    card_type   VARCHAR,
    card_number VARCHAR(16),
    balance     INTEGER,
    base_trips  INTEGER,
    dop_trips   INTEGER,
    CONSTRAINT pk_card PRIMARY KEY (id),
    CONSTRAINT fk_card_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS news
(
    id    INTEGER,
    date  VARCHAR,
    title VARCHAR,
    link  VARCHAR
);